var json={
    shadow: {
        size: 1024,
        usePercentageCloserFiltering: true,
    },
    materials : [
        {
            id: "default",
            name: "默认材质",
            type: 'material',
            diffuse: {},      // 漫反射, 漫反射和镜面材料需要创建光源。
            specular:{},    // 高光
            emissive:{},    // 自发光
            ambient:{},    // 环境, 环境颜色需要设置场景的环境颜色，提供环境背景照明
        },
        {
            id: "hightLight",
            name: "高亮材质",
            type: 'material',
            diffuse: {
                // color: BABYLON.Color3.FromHexString("#00ff00"),
            },
            specular:{},
            emissive:{},
            ambient:{},
            alpha: 1,
        },
        {
            id: "glass",
            name: "墙面",
            type: "material",
            subType: "PBRMaterial",
            params: {
                indexOfRefraction: 0.52,
                alpha: 0.45,
                directIntensity: 1,
            },
        },
        {
            id: "floorMaterial",
            name: "地板材质",
            type: 'material',
            ambientPath: "",
            offset: [0,0],
            scale: [16,6],
            diffuse: {
                color: BABYLON.Color3.FromHexString("#74b9ff"),
            },
            specular:{},
            emissive:{},
            ambient:{},
            alpha: 0.9,
        },
        {
            id: "wallMater",
            name: "墙面材质",
            type: 'material',
            diffuse: {
                color: BABYLON.Color3.FromHexString("#96CCFF"),
            },
            alpha: 0.6,
        },
        {
            id: "hide",
            name: "隐藏材质",
            type: 'material',
        }
    ],
    lights: [
        {
            id: "light1",
            name: "半球光",
            type: 'HemisphericLight',
            dir: [0, 1, 0],
            pos: [0,2,0],
            intensity: 0.85,
            shadow: false,
        },
        {
            id: "light2",
            name: "平行光",
            type: 'DirectionalLight',
            dir: [-0.25, -1, 0.25],  // x 对应前后方向; y 对应上下方向; z 对应左右方向
            pos: [25,25,25], // 位置大小对应模糊程度
            intensity: 1,
            shadow: true,
        }
    ],
    objects: [
        // {
        //     id: "floor",
        //     name: '地板',
        //     type: 'box',
        //     width: 100,
        //     height: 0.2,
        //     depth: 100,
        //     op: "+",
        //     pos: [0,0,0],
        //     rot: [0, 0, 0],
        //     style: 'floorMaterial',
        //     shadow: true,
        //     disable: true,
        // },
        // {
        //     id: "sphere1",
        //     name: '球',
        //     type: 'sphere',
        //     diameter: 2,  // 直径
        //     segments: 5,  // 分段数
        //     pos: [-2, 1.2, 0],
        //     style: 'glass',
        //     shadow: true,
        //     disable: true,
        // },
        // {
        //     id: "sphere2",
        //     name: '球',
        //     type: 'icoSphere',
        //     radius: 1,  // 半径
        //     subdivisions: 5,  // 分段数
        //     pos: [2, 1.2, 0],
        //     // style: 'floorMaterial',
        //     shadow: true,
        // },
        // {
        //     id: "box1",
        //     name: '立方体',
        //     type: 'box',
        //     width: 2,   // 对应 x
        //     height: 2,  // 对应 y
        //     depth: 2,   // 对应 z
        //     op: "+",
        //     pos: [5, 1.2, 5],
        //     style: 'glass',
        //     shadow: true,
        // },
        // {
        //     id: "door",
        //     name: '门',
        //     type: 'box',
        //     width: 0.2,
        //     height: 4,
        //     depth: 1.5,
        //     op: "+",
        //     pos: [-7.7, 2, 1],
        //     rot: [0, 0, 0],
        //     shadow: true,
        // },
        // {
        //     id: "floor1",
        //     name: '地面',
        //     type: 'box',
        //     width: 16,
        //     height: 0.2,
        //     depth: 52,
        //     op: "+",
        //     pos: [-6.5, -0.2, 25],
        //     style: 'floorMaterial',
        //     shadow: true,
        // },

        /////////// f1 /////////////
        {
            id: "f1",
            name: "1楼",
            type: 'plane',
            size: 0.01,
            pos: [0, 0, 0],
        },
        {
            id: "f1-wall-back",
            name: '墙-后',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [-13, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-front",
            name: '墙-前',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [0.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left1",
            name: '墙-左1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 0],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left8",
            name: '墙-右1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 50],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left2",
            name: '墙-左2',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 6],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left3",
            name: '墙-左3',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 12],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left4",
            name: '墙-左4',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 19],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left5",
            name: '墙-左5',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left6",
            name: '墙-左6',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 35],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left7",
            name: '墙-左7',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 42],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },

        {
            id: "f1-wall-left001",
            name: '墙-左001',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 7],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left002",
            name: '墙-左002',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left003",
            name: '墙-左003',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 20],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left004",
            name: '墙-左004',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 29],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left005",
            name: '墙-左005',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 36],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-left006",
            name: '墙-左006',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },


        {
            id: "f1-wall-back001",
            name: '墙-后001',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back002",
            name: '墙-后002',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back003",
            name: '墙-后003',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-8, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back004",
            name: '墙-后004',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 19.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back005",
            name: '墙-后005',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 24.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back006",
            name: '墙-后006',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 29.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back007",
            name: '墙-后007',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-8, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back008",
            name: '墙-后008',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-8, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back009",
            name: '墙-后009',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-8, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },



        {
            id: "f1-wall-back101",
            name: '墙-后101',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-4.5, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back102",
            name: '墙-后102',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-4.5, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back103",
            name: '墙-后103',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back104",
            name: '墙-后104',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6.5,
            pos: [-4.5, 2, 20.75],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back105",
            name: '墙-后105',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 28.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back106",
            name: '墙-后106',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-4.5, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back107",
            name: '墙-后107',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-4.5, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },
        {
            id: "f1-wall-back108",
            name: '墙-后108',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-4.5, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f1",
        },

        /////////// f2 /////////////

        {
            id: "f2",
            name: "2楼",
            type: 'plane',
            size: 0.01,
            pos: [0, 5, 0],
        },
        {
            id: "f2-wall-back",
            name: '墙-后',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [-13, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-front",
            name: '墙-前',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [0.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left1",
            name: '墙-左1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 0],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left8",
            name: '墙-右1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 50],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left2",
            name: '墙-左2',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 6],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left3",
            name: '墙-左3',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 12],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left4",
            name: '墙-左4',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 19],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left5",
            name: '墙-左5',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left6",
            name: '墙-左6',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 35],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left7",
            name: '墙-左7',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 42],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },

        {
            id: "f2-wall-left001",
            name: '墙-左001',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 7],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left002",
            name: '墙-左002',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left003",
            name: '墙-左003',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 20],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left004",
            name: '墙-左004',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 29],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left005",
            name: '墙-左005',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 36],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-left006",
            name: '墙-左006',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },


        {
            id: "f2-wall-back001",
            name: '墙-后001',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back002",
            name: '墙-后002',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back003",
            name: '墙-后003',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-8, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back004",
            name: '墙-后004',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 19.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back005",
            name: '墙-后005',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 24.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back006",
            name: '墙-后006',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 29.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back007",
            name: '墙-后007',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-8, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back008",
            name: '墙-后008',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-8, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back009",
            name: '墙-后009',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-8, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },



        {
            id: "f2-wall-back101",
            name: '墙-后101',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-4.5, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back102",
            name: '墙-后102',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-4.5, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back103",
            name: '墙-后103',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back104",
            name: '墙-后104',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6.5,
            pos: [-4.5, 2, 20.75],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back105",
            name: '墙-后105',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 28.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back106",
            name: '墙-后106',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-4.5, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back107",
            name: '墙-后107',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-4.5, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },
        {
            id: "f2-wall-back108",
            name: '墙-后108',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-4.5, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f2",
        },


        /////////// f3 /////////////
        {
            id: "f3",
            name: "3楼",
            type: 'plane',
            size: 0.01,
            pos: [0, 10, 0],
        },
        {
            id: "f3-wall-back",
            name: '墙-后',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [-13, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-front",
            name: '墙-前',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [0.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left1",
            name: '墙-左1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 0],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left8",
            name: '墙-右1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 50],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left2",
            name: '墙-左2',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 6],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left3",
            name: '墙-左3',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 12],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left4",
            name: '墙-左4',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 19],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left5",
            name: '墙-左5',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left6",
            name: '墙-左6',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 35],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left7",
            name: '墙-左7',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 42],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },

        {
            id: "f3-wall-left001",
            name: '墙-左001',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 7],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left002",
            name: '墙-左002',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left003",
            name: '墙-左003',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 20],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left004",
            name: '墙-左004',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 29],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left005",
            name: '墙-左005',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 36],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-left006",
            name: '墙-左006',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },


        {
            id: "f3-wall-back001",
            name: '墙-后001',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back002",
            name: '墙-后002',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back003",
            name: '墙-后003',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-8, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back004",
            name: '墙-后004',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 19.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back005",
            name: '墙-后005',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 24.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back006",
            name: '墙-后006',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 29.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back007",
            name: '墙-后007',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-8, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back008",
            name: '墙-后008',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-8, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back009",
            name: '墙-后009',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-8, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },



        {
            id: "f3-wall-back101",
            name: '墙-后101',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-4.5, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back102",
            name: '墙-后102',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-4.5, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back103",
            name: '墙-后103',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back104",
            name: '墙-后104',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6.5,
            pos: [-4.5, 2, 20.75],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back105",
            name: '墙-后105',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 28.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back106",
            name: '墙-后106',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-4.5, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back107",
            name: '墙-后107',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-4.5, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },
        {
            id: "f3-wall-back108",
            name: '墙-后108',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-4.5, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f3",
        },

        /////////////////// f4 ////////////////

        {
            id: "f4",
            name: "4楼",
            type: 'plane',
            size: 0.01,
            pos: [0, 15, 0],
        },
        {
            id: "f4-wall-back",
            name: '墙-后',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [-13, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-front",
            name: '墙-前',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [0.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left1",
            name: '墙-左1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 0],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left8",
            name: '墙-右1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 50],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left2",
            name: '墙-左2',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 6],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left3",
            name: '墙-左3',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 12],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left4",
            name: '墙-左4',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 19],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left5",
            name: '墙-左5',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left6",
            name: '墙-左6',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 35],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left7",
            name: '墙-左7',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 42],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },

        {
            id: "f4-wall-left001",
            name: '墙-左001',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 7],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left002",
            name: '墙-左002',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left003",
            name: '墙-左003',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 20],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left004",
            name: '墙-左004',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 29],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left005",
            name: '墙-左005',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 36],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-left006",
            name: '墙-左006',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },


        {
            id: "f4-wall-back001",
            name: '墙-后001',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back002",
            name: '墙-后002',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back003",
            name: '墙-后003',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-8, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back004",
            name: '墙-后004',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 19.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back005",
            name: '墙-后005',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 24.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back006",
            name: '墙-后006',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 29.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back007",
            name: '墙-后007',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-8, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back008",
            name: '墙-后008',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-8, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back009",
            name: '墙-后009',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-8, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },



        {
            id: "f4-wall-back101",
            name: '墙-后101',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-4.5, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back102",
            name: '墙-后102',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-4.5, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back103",
            name: '墙-后103',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back104",
            name: '墙-后104',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6.5,
            pos: [-4.5, 2, 20.75],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back105",
            name: '墙-后105',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 28.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back106",
            name: '墙-后106',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-4.5, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back107",
            name: '墙-后107',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-4.5, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },
        {
            id: "f4-wall-back108",
            name: '墙-后108',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-4.5, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f4",
        },

        /////////////// f5 ///////////////////
        {
            id: "f5",
            name: "5楼",
            type: 'plane',
            size: 0.01,
            pos: [0, 20, 0],
        },
        {
            id: "f5-wall-back",
            name: '墙-后',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [-13, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-front",
            name: '墙-前',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [0.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left1",
            name: '墙-左1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 0],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left8",
            name: '墙-右1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 50],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left2",
            name: '墙-左2',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 6],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left3",
            name: '墙-左3',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 12],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left4",
            name: '墙-左4',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 19],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left5",
            name: '墙-左5',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 25],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left6",
            name: '墙-左6',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 35],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left7",
            name: '墙-左7',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-10.5, 2, 42],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },

        {
            id: "f5-wall-left001",
            name: '墙-左001',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 7],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left002",
            name: '墙-左002',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left003",
            name: '墙-左003',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 20],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left004",
            name: '墙-左004',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 29],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left005",
            name: '墙-左005',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 36],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-left006",
            name: '墙-左006',
            type: 'box',
            width: 5,
            height: 4,
            depth: 0.2,
            pos: [-2, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },


        {
            id: "f5-wall-back001",
            name: '墙-后001',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back002",
            name: '墙-后002',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back003",
            name: '墙-后003',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-8, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back004",
            name: '墙-后004',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 19.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back005",
            name: '墙-后005',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-8, 2, 24.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back006",
            name: '墙-后006',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-8, 2, 29.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back007",
            name: '墙-后007',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-8, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back008",
            name: '墙-后008',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-8, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back009",
            name: '墙-后009',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-8, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },



        {
            id: "f5-wall-back101",
            name: '墙-后101',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 3,
            pos: [-4.5, 2, 1.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back102",
            name: '墙-后102',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 4,
            pos: [-4.5, 2, 6.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back103",
            name: '墙-后103',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 13],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back104",
            name: '墙-后104',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6.5,
            pos: [-4.5, 2, 20.75],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back105",
            name: '墙-后105',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 6,
            pos: [-4.5, 2, 28.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back106",
            name: '墙-后106',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 5,
            pos: [-4.5, 2, 35.5],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back107",
            name: '墙-后107',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 7,
            pos: [-4.5, 2, 43],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },
        {
            id: "f5-wall-back108",
            name: '墙-后108',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 2,
            pos: [-4.5, 2, 49],
            rot: [0, 0, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f5",
        },

        //////////// f6 /////////////
        {
            id: "f6",
            name: "6楼",
            type: 'plane',
            size: 0.01,
            pos: [0, 25, 0],
        },
        {
            id: "f6-wall-back",
            name: '墙-后',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [-13, 2, 25],
            style: 'wallMater',
            shadow: true,
            parent: "f6",
        },
        {
            id: "f6-wall-front",
            name: '墙-前',
            type: 'box',
            width: 0.2,
            height: 4,
            depth: 50,
            pos: [0.5, 2, 25],
            style: 'wallMater',
            shadow: true,
            parent: "f6",
        },
        {
            id: "f6-wall-left1",
            name: '墙-左1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 0],
            style: 'wallMater',
            shadow: true,
            parent: "f6",
        },
        {
            id: "f6-wall-right1",
            name: '墙-右1',
            type: 'box',
            width: 14,
            height: 4,
            depth: 0.2,
            pos: [-6.25, 2, 50],
            style: 'wallMater',
            shadow: true,
            parent: "f6",
        },



        // {
        //     id: "f1-wall-south",
        //     name: '墙-南',
        //     type: 'box',
        //     width: 0.2,
        //     height: 24,
        //     depth: 5,
        //     op: "+",
        //     pos: [0, 7, 2.5],
        //     rot: [0, 0, Math.PI / 2],
        //     style: 'floorMaterial',
        //     shadow: true,
        // },
        // {
        //     id: "f1-wall-north",
        //     name: '墙-北',
        //     type: 'box',
        //     width: 0.2,
        //     height: 24,
        //     depth: 5,
        //     op: "+",
        //     pos: [0, -7, 2.5],
        //     rot: [0, 0, Math.PI / 2],
        //     style: 'floorMaterial',
        //     shadow: true,
        // },
        // {
        //     id: "f1-wall-north-window1",
        //     name: '墙-北',
        //     type: 'box',
        //     width: 0.2,
        //     height: 2,
        //     depth: 5,
        //     op: "-",
        //     pos: [0, -7, 2.5],
        //     rot: [0, 0, Math.PI / 2],
        //     style: 'floorMaterial',
        //     shadow: true,
        // }
    ],
}